name: icar
description: "调整智能车运行参数，控制智能车的各项行为。"
publish_to: 'none'

version: 0.1.0+3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartssh2: ^2.11.0
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


